export const colors = [
  {
    title: 'RGB to HEX / HEX to RGB',
    content:
      "<div class='mb-4'><p class='font-bold mb-2'>HEX color</p><p>Hex color code is a 6 digits hexadecimal (base 16) number:</p><p class='italic m-2'>RRGGBB<sub>16</sub></p><p>The 2 left digits represent the red color.</p><p>The 2 middle digits represent the green color.</p><p>The 2 right digits represent the blue color.</p></div><div class='mb-4'><p class='font-bold mb-2'>RGB color</p><p>The RGB color is a combination of <strong>R</strong>ed, <strong>G</strong>reen and <strong>B</strong>lue colors:</p><p class='italic m-2'>(R, G, B)</p><p>The red, green and blue use 8 bits each, which have integer values from 0 to 255. So the number of colors that can be generated is:</p><p class='italic m-2'>256×256×256 = 16777216 = 1000000<sub>16</sub></p></div><div class='mb-4'><p class='font-bold mb-2'>Hex to RGB conversion</p><ul class='space-y-1 list-disc list-inside mb-8'><li>Get the 2 left digits of the hex color code and convert to decimal value to get the red color level.</li><li>Get the 2 middle digits of the hex color code and convert to decimal value to get the green color level.</li><li>Get the 2 right digits of the hex color code and convert to decimal value to get the blue color level.</li></ul></div><div class='mb-4'><p class='font-bold mb-2'>RGB to HEX conversion</p><ul class='space-y-1 list-disc list-inside mb-8'><li>Convert the red, green and blue color values from decimal to hexadecimal.</li><li>Concatenate the hex values of the red, green and blue together.</li></ul></div>",
  },
  {
    title: 'RGB to HSV / HSV to RGB',
    content:
      "<div class='mb-4'><p class='font-bold mb-2'>RGB to HSV formula:</p><p>The R,G,B values are divided by 255 to change the range from [0,255] to [0,1]</p><p class='italic m-2'>R' = R/255</p><p class='italic m-2'>G`= G/255</p><p class='italic m-2'>B`= B/255</p><p class='italic m-2'>Cmax = max(R', G', B')</p><p class='italic m-2'>Cmin = min(R', G', B')</p><p class='italic m-2'>Δ = Cmax - Cmin</p><p>Hue calculation:</p><p class='italic m-2'>if Δ = 0 => H = 0</p><p class='italic m-2'>if Cmax = R' => H = 60º x (G' - B')/Δ</p><p class='italic m-2'>if Cmax = G' => H = 2 + 60º x (B' - R')/Δ</p><p class='italic m-2'>if Cmax = B' => H = 4 + 60º x (R' - B')/Δ</p><p>Saturation calculation:</p><p class='italic m-2'>if Cmax = 0 => S = 0</p><p class='italic m-2'>if Cmax &#8800; 0 => S = Δ/Cmax</p><p>Value calculation:</p> <p class='italic'>V = Cmax</p></div><div class='mb-4'><p class='font-bold mb-2'>HSV to RGB formula:</p><p>HSV values are on [0,360], [0,1] and [0,1] ranges respectively.</p><p class='italic m-2'>C = V × S</p><p class='italic m-2'>X = C × (1 - |(H / 60°) mod 2 - 1|)</p><p class='italic m-2'>m = V - C</p><p class='italic m-2'>0º &#8924; H < 60º => (R', G', B') = (C, X, 0) </p><p class='italic m-2'>60º &#8924; H < 120º => (R', G', B') = (X, C, 0) </p><p class='italic m-2'>120º &#8924; H < 180º => (R', G', B') = (0, C, X) </p><p class='italic m-2'>180º &#8924; H < 240º => (R', G', B') = (0, X, C) </p><p class='italic m-2'>240º &#8924; H < 300º => (R', G', B') = (X, 0, C) </p><p class='italic m-2'>300º &#8924; H < 360º => (R', G', B') = (C, 0, X) </p><p class='italic m-2'>(R,G,B) = ((R'+m)×255, (G'+m)×255, (B'+m)×255)</p></div",
  },
  {
    title: 'RGB to HSL / HSL to RGB',
    content:
      "<div class='mb-4'><p class='font-bold mb-2'>RGB to HSL formula:</p><p>The R,G,B values are divided by 255 to change the range from [0,255] to [0,1]</p><p class='italic m-2'>R' = R/255</p><p class='italic m-2'>G`= G/255</p><p class='italic m-2'>B`= B/255</p><p class='italic m-2'>Cmax = max(R', G', B')</p><p class='italic m-2'>Cmin = min(R', G', B')</p><p class='italic m-2'>Δ = Cmax - Cmin</p><p>Hue calculation:</p><p class='italic m-2'>if Δ = 0 => H = 0</p><p class='italic m-2'>if Cmax = R' => H = 60º x (G' - B')/Δ</p><p class='italic m-2'>if Cmax = G' => H = 2 + 60º x (B' - R')/Δ</p><p class='italic m-2'>if Cmax = B' => H = 4 + 60º x (R' - B')/Δ</p><p>Saturation calculation:</p><p class='italic mb-2'>if Δ = 0 => S = 0</p><p class='italic mb-2'>if Δ <> 0 => S = Δ / (1 - 2L -1|)</p><p>Lightness calculation:</p><p class='italic mb-2'>L = (Cmax + Cmin) / 2</p><div><div><p class='font-bold mb-2'>HSL to RGB formula:</p><p>HSL values are on [0,360], [0,1] and [0,1] ranges respectively.</p><p class='italic m-2'>C = (1 - |2L - 1|) × S</p><p class='italic m-2'>X = C × (1 - |(H / 60°) mod 2 - 1|)</p><p class='italic m-2'>m = L - C/2</p><p class='italic m-2'>0º &#8924; H < 60º => (R', G', B') = (C, X, 0) </p><p class='italic m-2'>60º &#8924; H < 120º => (R', G', B') = (X, C, 0) </p><p class='italic m-2'>120º &#8924; H < 180º => (R', G', B') = (0, C, X) </p><p class='italic m-2'>180º &#8924; H < 240º => (R', G', B') = (0, X, C) </p><p class='italic m-2'>240º &#8924; H < 300º => (R', G', B') = (X, 0, C) </p><p class='italic m-2'>300º &#8924; H < 360º => (R', G', B') = (C, 0, X) </p><p class='italic m-2'>(R,G,B) = ((R'+m)×255, (G'+m)×255, (B'+m)×255)</p></div>",
  },
  {
    title: 'HEX to HSV / HSV to HEX',
    content:
      "<div class='mb-4'>The easiest and more straighforward method is to transform the HEX/HSV values to RGB as a proxy and back to the desired code color</div>",
  },
  {
    title: 'HEX to HSL / HSL to HEX',
    content:
      "<div class='mb-4'>The easiest and more straighforward method is to transform the HEX/HSL values to RGB as a proxy and back to the desired code color</div>",
  },
  {
    title: 'HSV to HSL / HSL to HSV',
    content:
      "<div class='mb-4'><p class='font-bold mb-2'>HSV to HSL formula:</p><p>HSV values are on H = [0,360], S = [0,1] and V = [0,1] ranges respectively.</p><p class='italic mb-2'>H<sub>HSL</sub> = H<sub>HSV</sub></p><p class='italic mb-2'>L = ((2 - S) * V) / 2</p><p class='italic mb-2'>if L = 0 => S<sub>HSL</sub> = S<sub>HSV</sub></p><p class='italic mb-2'>if L = 1 => S<sub>HSL</sub> = 0</p><p class='italic mb-2'>if 0 ⋜ L < 0.5 => S<sub>HSL</sub> = (SS<sub>HSV</sub> * V) / (L * 2)</p><p class='italic mb-2'>if 0.5 ⋜ L < 1 => S<sub>HSL</sub> = (SS<sub>HSV</sub> * V) / (2 - L * 2)</p></div><div class='mb-4'><p class='font-bold mb-2'>HSL to HSV formula:</p><p>HSL values are on H = [0,360], S = [0,1] and L = [0,1] ranges respectively.</p><p class='italic mb-2'>H<sub>HSV</sub> = H<sub>HSL</sub></p><p class='italic mb-2'>V = L + S<sub>HSL</sub> x Min(L, 1 - L)<sub>HSL</sub></p><p ckass='italic mb-2'>if V = 0 => S<sub>HSV</sub> = 0</p><p ckass='italic mb-2'>if V ≠ 0 => S<sub>HSV</sub> = 2 -2L/V</p></div>",
  },
]
